### ISSUE TITLE
Atlas infinite loop?

### ISSUE THREAD

**Issue by eadmaster** [Normmatt/Guru-Logic-Champ-GBA-Translation#1]
when running the build.bat script, Atlas.exe goes into infinite loop apparently...

**Comment by hippydave** [comment]
Same problem here, any ideas? Thanks

**Comment by Normmatt** [comment]
If I remember correctly its your git client messing with the newline format of files.

**Comment by hippydave** [comment]
Looks like you're right, converting the scripts to CRLF seems to have fixed it - many thanks!

**Comment by eadmaster** [comment]
EDIT: Ok, it's working now after converting the EOLs of all files in the "script" dir...
